node {
    stage("Checkout - ${env.BRANCH_NAME}") {
        checkout scm
    }

    stage('Build and create docker image'){
        sh './gradlew clean docker'
    }

    def namespace = "${env.DEV_NS}"
    if ("${env.BRANCH_NAME}" == "release/qc") {
        namespace = "${env.QC_NS}"
    }

    stage("Tag docker image - ${namespace}/user-api"){
        sh "docker tag f8/user-api ${env.REGISTRY}/${namespace}/user-api"
    }

    stage("Push docker image - ${namespace}/user-api") {
        sh "docker push ${env.REGISTRY}/${namespace}/user-api"
    }

    stage("Cleanup") {
        sh "docker rmi ${env.REGISTRY}/${namespace}/user-api"
    }
}