package asia.cmg.f8.session.entity;

public enum PopupScheduleCase {

	HAS_SESSION_HAS_ACTIVE_OR_INACTIVE_PACKAGES,
	NO_SESSION_HAS_ACTIVE_PACKAGES,
	NO_SESSION_HAS_INACTIVE_PACKAGES,
	NO_SESSION_NO_PACKAGES,
	HAS_PENDING_SESSION
}
