package asia.cmg.f8.common.spec.notification;

public enum NotificationType {
	LIKE_POST,
	COMMENT_POST,
	LIKE_COMMENT,
	FOLLOW,
	CREATE_POST,
	TRANSFER_SESSION,
	CHANGE_SESSION_STATUS,
	ORDER_SUBSCRIPTION,
	ORDER_CREDIT,
	APPROVE_DOC,
	START_SESSION,
	ORDER_COMLETED,
	CHAT,
	LISA_ADMIN,
	PURCHASE_PACKAGE,
	UPGRADE_WALLET,
	EXPIRE_PACKAGE,
	CLASS_STARTING_REMIND,
	CLASS_EXPIRE_REMIND,
	SESSION_PT_CONFIRM,
	SESSION_CONFIRMED_EU
}
